language: node_js

node_js: 
  - 'node'

before_deploy:
  - 'npm run build'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: build
  fqdn: 'akshitkrnagpal.com'
  name: 'akshitkrnagpal'
  email: 'akshitkrnagpal@gmail.com'
  on:
    branch: master