# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npx ncu -u
    - run: npm install
    - uses: actions-js/push@v1.2
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        author_email: akshitkrnagpal@gmail.com
        author_name: akshitkrnagpal
        message: Updated Dependencies
      
  
