name: Build and Deploy
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Build
              run: npm install && npm run build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v2
              env:
                  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: public
